name: Deploy NGINX Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build and run container
        run: |
          docker build -t nginx-backend:latest .
          docker stop nginx-backend || true
          docker rm nginx-backend || true
          docker run -d -p 8080:80 --name nginx-backend nginx-backend:latest
