name: Deploy NGINX App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Stop and remove previous container
        run: docker rm -f nginx-backend || true

      - name: Build latest Docker image
        run: docker build -t nginx-backend:latest .

      - name: Run production container
        run: |
          docker run -d \
            --name nginx-backend \
            -p 8080:80 \
            nginx-backend:latest
