name: Test and Merge NGINX

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cleanup old container and free port 8080
        run: |
          echo "Stopping and removing any existing container named nginx-backend-test"
          docker stop nginx-backend-test || true
          docker rm nginx-backend-test || true

          echo "Killing any process using port 8080"
          pids=$(lsof -t -i:8080) || true
          if [ ! -z "$pids" ]; then
            echo "Found processes on port 8080: $pids"
            kill -9 $pids
          fi

          # Wait until port 8080 is free
          echo "Waiting for port 8080 to be free..."
          for i in {1..10}; do
            if ! lsof -i:8080 >/dev/null; then
              echo "Port 8080 is now free"
              break
            else
              echo "Port 8080 still in use, waiting..."
              sleep 3
            fi
          done

      - name: Build Docker image
        run: docker build -t nginx-backend:test .

      - name: Run container and health check
        run: |
          docker run -d --name nginx-backend-test -p 8080:80 nginx-backend:test
          sleep 10
          curl --fail http://localhost:8080 || (docker logs nginx-backend-test && exit 1)
          docker stop nginx-backend-test
          docker rm nginx-backend-test

  merge:
    needs: test
    runs-on: self-hosted
    if: success()

    steps:
      - name: Setup Git identity
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci@local.test"

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout main branch
        run: git checkout main

      - name: Merge test branch into main
        run: git merge test

      - name: Push merged changes
        run: git push origin main
