name: Test and Merge NGINX

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean any old test container
        run: docker rm -f nginx-backend-test || true

      - name: Build Docker image
        run: docker build -t nginx-backend:test .

      - name: Run container and health check
        run: |
          docker run -d --name nginx-backend-test -p 8081:80 nginx-backend:test
          sleep 10
          curl --fail http://localhost:8080 || (docker logs nginx-backend-test && exit 1)
          docker stop nginx-backend-test
          docker rm nginx-backend-test

  promote:
    needs: test
    runs-on: self-hosted
    if: success()

    steps:
      - name: Set up Git identity
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci@local.test"

      - name: Checkout main branch
        run: |
          git fetch origin
          git checkout main

      - name: Merge test into main with clean strategy
        run: |
          git merge origin/test --strategy=recursive --strategy-option=theirs --allow-unrelated-histories || true
          git add .
          git commit -m "Automated merge from test into main [CI]" || true

      - name: Push merge result
        run: git push origin main
