- name: Cleanup old container and free port 8080
  run: |
    docker stop nginx-backend-test || true
    docker rm nginx-backend-test || true

    pids=$(lsof -t -i:8080) || true
    if [ ! -z "$pids" ]; then
      echo "Killing processes on port 8080: $pids"
      kill -9 $pids
    fi

    sleep 3

- name: Build Docker image
  run: docker build -t nginx-backend:test .

- name: Run container and health check
  run: |
    docker run -d --name nginx-backend-test -p 8080:80 nginx-backend:test
    sleep 5
    curl --fail http://localhost:8080 || exit 1
    docker stop nginx-backend-test
    docker rm nginx-backend-test
