- name: Cleanup old test container
  run: |
    docker stop nginx-backend-test || true
    docker rm nginx-backend-test || true

- name: Run and health check
  run: |
    docker run -d --name nginx-backend-test -p 8080:80 nginx-backend:test
    sleep 5
    curl --fail http://localhost:8080 || exit 1
    docker stop nginx-backend-test
    docker rm nginx-backend-test
